great_ape_safe/great_ape_safe.py, scripts/issue/40/badger_emissions_week_4.py
=> easy transfer script for badger emissions

great_ape_safe/ape_api/badger.py, scripts/badger/whitelist.py
to solve #51 :
```
brownie run badger/whitelist single_sett 0x6F76C6A1059093E21D8B1C13C4e20D8335e2909F 0xfd05D3C7fe2924020620A8bE4961bBaA747e6305
```
=> add whitelist func to `Badger` plus reusable script

helpers/addresses.py
Adding ops_deployer7 for handling deployment of Badger and Digg voting shares
=> chore: add ops deployer

interfaces/badger/IStrategy.sol, scripts/issue/67/set_fees_strat_and_gov.py
Tackles #67 
Command:
```
brownie run issue/67/set_fees_strat_and_gov
```
=> Script to modify perf fee strat & gov in few strategiest where is sending to deployer wallet

great_ape_safe/ape_api/pancakeswap_v2.py, great_ape_safe/great_ape_safe.py, helpers/addresses.py, scripts/issue/33/swap_eps_for_bnb.py
Tackles #33 
Command:
```
brownie run --network bsc-main-fork scripts/issue/33/swap_eps_for_bnb
```
**Note:** I am getting timeout while testing locally, so i am unable of getting till the end rn. Would appreciate if @jorijnsmit @sajanrajdev can run it and let me know if you have same issue
Err:
```
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8545): Read timed out. (read timeout=10)
```
=> Add pancakeswap class and script to swap eps -> bnb

helpers/addresses.py, scripts/badger/swap_bribes_for_bvecvx.py
=> add func to manually swap t token through curve v2

helpers/addresses.py, scripts/issue/97/migrate_ops_deprecated.py
Tackles #97 
Command:
```
brownie run issue/97/migrate_ops_deprecated
```
=> Add script to migrate the jersey nft and eth funds

scripts/gnosis/scrape_tokens.py
turn list into set to remove duplicate lp tokens present in both treasury_tokens and sett_vaults.
=> fix: remove duplicates from `token_list`

data/badger/timelock/upgrade_veCVX_strategy_V1_5/0xf079ad6ae3cb7882db7fa8a9a543c565735a6dcdf76adfc490ed41e559c9102b.json
=> queued in timelock as per nonce 1005

great_ape_safe/ape_api/uni_v2.py, scripts/issue/159/withdraw_9_digg_from_tcl.py
solve #159 
withdraws exactly 9 digg from the treasury vault slp (and corresponding wbtc) to the treasury ops wallet.
added destination parameter to univ2 class methods.
=> withdraw 9 digg from tcl, add dest feat to univ2 class

great_ape_safe/ape_api/curve.py, great_ape_safe/ape_api/curve_v2.py, scripts/issue/34/issue34.py
had to do some hot fixes yesterday in order to run issue34.py
=> solve name collision on curve v1 and v2 registry

scripts/issue/71/consolidate_badger.py
Added tolerance to balance checker on Badger consolidation script
=> feat: add tolerance to balance checker

great_ape_safe/ape_api/rari.py, scripts/issue/178/changecf.py
**solves #178**. additionally, make units in `Rari` more consistent with each other
=> update fDOLA collateral factor

scripts/issue/187/update_rari_cf.py
=> set cf of remaining stables in Rari Fuse to 85%

scripts/badger/thresher.py
=> amendmends needed to successfully run thresher

scripts/TCL/positionData/198350_2022-02-28.json, scripts/issue/32/top_up_lowest_range_uni_v3.py
Tackles #32 topping-up task
Command: 
```
brownie run issue/32/top_up_lowest_range_uni_v3
```
=> Add script for topping up lowest range

scripts/issue/222/dogfood_bvecvx.py
**solves #222**.
`brownie run issue/222/dogfood_bvecvx.py`
=> script to dogfood rest of bvecvx

great_ape_safe/ape_api/badger.py
should save considerable amount of gas vs the for looping we are doing now.
waiting with review until there actually are claimables (week 12) so we can run onfork.
=> leverage votium's claimMulti func to save gas

scripts/issue/250/claim_rewards.py
**solves #250;** pending univ3 and convex rewards are claimed from vault and transferred to trops
=> claim vault rewards for univ3/convex

scripts/issue/254/deposit_factory.py
**solves #254**, very similar to #34 with cleaned up code. sufficient badger already in trops and required wbtc is siphoned from bibbtc
`brownie run issue/254/deposit_factory`
=> script to deposit 50k badger & equal parts wbtc into our factory pool

helpers/addresses.py
This PR relates to issuse #274 
Adds addresses for the BADGER/wBTC Crv LP vault and the new vestedCVX strat address.
=> feat: updates badger crv and vestedcvx addresses

scripts/emissions/weekly_emissions.py
=> Update emission mainnet script as bip-87

scripts/emissions/bribes_emissions.py, scripts/issue/333/swap_dfd_comp_for_oxd.py
steps and details in #333 
last func still has to be written (the actual oxd swap on fantom)
=> first couple of steps in oxd trade

helpers/addresses.py, scripts/issue/340/unwrap_3pool_for_finops.py
=> unwrap some 3pool to send usdc to payments

scripts/issue/375/withdraw_aave_to_payments.py
this to cover q2 budget, see #375
=> withdraw ausdc from aave to payments msig

scripts/badger/refill_gas_ftm.py
=> increase ops_botsquad refill amount to 500 ftm

great_ape_safe/ape_api/uni_v2.py, helpers/addresses.py, scripts/issue/367/dogfood_oxd.py
-script for #367 - `oxd` -> `bveoxd` -> `bveoxd/oxd lp` -> `bbveoxd/oxd`
-`univ2.add_liquidity` update to work with solidly
-currently script still leaves ~~**~1600 oxd** idle, so this is draft for now~~, ~~now is down to 400 oxd~~ 46 oxd
=> dogfood oxd

helpers/addresses.py, interfaces/swapr/IERC20StakingRewardsDistribution.sol, scripts/swapr/staking_contract_update.py
Addresses #392
```
Events In This Transaction
--------------------------
├── Gnosis Safe (0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F)
│   └── SafeMultiSigTransaction
│       ├── to: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
│       ├── value: 0
│       ├── data: 0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001e40085386c3ce0679b035a9f8f17f531c076d0b35954000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000d090a6b7651d9e51fe4d25c6756623613fdb79500043942ceae98cc7485b48a37fbb1aa5035e1c8b46000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> Update swapr staking contracts (April)

great_ape_safe/ape_api/rari.py, scripts/issue/382/update_liq_incentive.py
handles #382 
```sh
brownie run issue/382/update_liq_incentive main <new_incentive> -I
```
=> script to set new liquidation incentive in rari

scripts/badger/topups/week_18.py
note: badger top-up relies on month 5 badger top-up to trops first (#311, #422)
=> week 18 top-ups csv-less

great_ape_safe/ape_api/balancer.py, tests/balancer/conftest.py, tests/balancer/test_balancer_deposit.py, tests/balancer/test_balancer_withdraw.py
dont break your head too much over that BAL#506, i think it is a shortcoming of the balpy module.
maybe write one more unit test for the claim? after i think at least all reqs of the ticket are met: #412
=> fix: typos

helpers/addresses.py, scripts/issue/433/bribe_badger_balancer_gauge.py
Tackles #433 
```
brownie run issue/433/bribe_badger_balancer_gauge
```
=> Add briber script HH - balancer

scripts/badger/topups/week_19.py
=> week 19 topups

helpers/addresses.py, scripts/issue/354/upgrade_remaining_setts_pause.py
Issue: https://github.com/Badger-Finance/badger-multisig/issues/354
Upgrade non-upgraded setts with ability to be paused by GAC.
=> upgrade sett logics for gac

scripts/badger/bridge_out_arbitrum_fees/badger_to_techops.py, scripts/badger/bridge_out_arbitrum_fees/bridge_out_erc20.py, scripts/badger/bridge_out_arbitrum_fees/withdraw_arb.py
@jalbrekt85 i had to make some small changes to get script to run locally, thought i might pr it to save time.
still one caveat though; `bDXS.withdrawAll()` gives me a `blockLocked`!
@petrovska-petro thoughts?
=> small bugs to get arb1 fees wd script to run locally

scripts/badger/topups/week_20.py
=> week 20 topups

helpers/addresses.py, interfaces/arbitrum/ICrvGaugeFactory.sol, interfaces/arbitrum/ICrvStrategy.sol, interfaces/arbitrum/ICurveGauge.sol, scripts/issue/452/upgrade_arb_crv_gauges.py
Handles #452 
Setting gauge and simulating harvest for tricrypto and renbtc crv strategies on arb:
=> feat: upgrade arb crv strats to new gauge

great_ape_safe/ape_api/balancer.py, scripts/issue/413/stablefarm_rebalance.py
delay bal3pool deposit in light of https://forum.balancer.fi/t/vulnerability-disclosure/3179
=> feat: delay bal3pool deposit, add separate stake method

scripts/issue/479/stop_digg_emissions_q2.py
Tackles #479 
```
brownie run issue/479/stop_digg_emissions_q2
```
=> Stop digg emissions in q2 - bip 92

scripts/issue/488/transfer_balancer_tcl.py
Tackles #488 
```
brownie run issue/488/transfer_balancer_tcl
```
=> Move balancer tcl to vault_msig & stake dust

helpers/addresses.py, interfaces/chainlink/ILinkToken.sol, interfaces/chainlink/IUpkeepRegistrationRequests.sol, scripts/chainlink/register_upkeep.py, scripts/deployment/deploy_autonomous_dripper.py
i confirmed with the chainlink team that the `encryptedEmail` and `source` parameters can remain null.
=> dripper deloyed; script to register it as an upkeep

scripts/issue/365/register_vaults.py
Registers Fantom vaults on the v2 registry with the proper parameters
#365 partial implementation
```
Running 'scripts/issue/365/register_vaults.py::register_vaults'...
['0xFce6e3115D84c94df98BD286C1C67279dc021361', 'v1', 'name=%F0%9F%91%BB%20BOO/xBOO,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0x0d6f70d397978871c91df42226c716978a69163493593d9e6c7d0cb4f6f37058
Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
Transaction confirmed   Block: 39186948   Gas used: 228439 (1.90%)
Promote: 0xFce6e3115D84c94df98BD286C1C67279dc021361 (v1) to 0
['0xB6D63A4e5Ca740e96C26AdAbcAc73BE78Ee39Dc5', 'v1', 'name=WBTC/renBTC,protocol=Solidex,behavior=Compounder', 2]
Transaction sent: 0xeff17c028a18702e5dce7a70646fc35ef8e25ee322177811bad3b893dbb9c604
Gas price: 0.0 gwei   Gas limit: 12000000 …
```
=> feat: register fantom vaults

helpers/addresses.py, interfaces/badger/IUFragments.sol, scripts/issue/520/upgrade_digg.py
Closes Issue #520 
Upgrades Digg to new logic with oneTimeMint, Sweep and Toggle Rebase
Run queue with:
```
brownie run scripts/issue/520/upgrade_digg.py
```
Run execution with:
```
brownie run scripts/issue/520/upgrade_digg.py main false
```
Run simulation with:
```
brownie run scripts/issue/520/upgrade_digg.py main false true
```
=> Digg upgrade script

scripts/issue/500/rari_withdraw.py
we all missed this bug: `to=registry.fusdc.address` so had to hack it anyway.
=> feat: consolidate rari redeems into one multicall

data/badger/timelock/upgrade_digg/0x51de3da020167d76de08064d93980c44c702090fc65328bdda9dc020f6149dc6.json, data/badger/timelock/upgrade_digg/0xd9853070e6a60380630a6ef82b22a32ef5a6e75bd42da5a831117f1a03c56378.json, scripts/issue/520/upgrade_digg.py
=> feat: digg upgrade data

scripts/issue/549/withdraw_3pool.py
=> withdraw 3pool usdc from trops to vault

helpers/addresses.py, interfaces/badger/ITheVaultWithoutTree.sol, scripts/issue/543/upgrade_ftm_emitting_vault.py
This PR closes issue #543 
To run upgrade:
```
brownie run scripts/issue/543/upgrade_ftm_emitting_vault.py --network ftm-main-fork
```
To run simulation:
```
brownie run scripts/issue/543/upgrade_ftm_emitting_vault.py main true --network ftm-main-fork
```
=> feat: upgrade rewards ftm vault

scripts/issue/441/mint_lowest_range_uni_v3.py
Tackles #441 
```
brownie run issue/441/mint_lowest_range_uni_v3
```
**Note:** somehow thought this one i pushed it. but searching for posting seems it is not the case
=> Include script to deploy 0.0000313 - 0.000063 range univ3

helpers/addresses.py, scripts/issue/554/upgrade_bveOXD_LP.py
Closes issue #554 
Run with:
```
brownie run scripts/issue/554/upgrade_bveOXD_LP.py --netowork ftm-main-fork
```
Run simulation with:
```
brownie run scripts/issue/554/upgrade_bveOXD_LP.py main true --netowork ftm-main-fork
```
=> Upgrade bveOXD/OXD script

helpers/addresses.py
addresses https://github.com/Badger-Finance/badger-multisig/issues/571
=> chore: udpate swapr staking contracts for june

tests/aave/conftest.py, tests/balancer/conftest.py, tests/balancer/test_balancer_claim.py, tests/balancer/test_balancer_deposit.py, tests/balancer/test_balancer_withdraw.py, tests/compound/conftest.py, tests/conftest.py, tests/convex/conftest.py, tests/curve/conftest.py, tests/curve/test_curve_deposit.py, tests/rari/conftest.py
solves #389 and organizes protocol specific fixtures
=> refactor tests

helpers/addresses.py
https://github.com/Badger-Finance/badger-infra/issues/4
https://github.com/Badger-Finance/badger-infra/issues/5
=> chore: add dripper addresses

helpers/addresses.py, interfaces/badger/IVestedAura.sol, scripts/issue/577/upgrade_graviaura_strat.py
Addresses #577
Old logic: [0x6f87739746c2cAD5Fc9dbd7dfA7a41eFd91135D7](https://etherscan.io/address/0x6f87739746c2cAD5Fc9dbd7dfA7a41eFd91135D7)
New logic: [0x0d724e8aee6f73b35a596c8c947c92c75eac7818](https://etherscan.io/address/0x0d724e8aee6f73b35a596c8c947c92c75eac7818)
Diff:
- https://github.com/Badger-Finance/vested-aura/compare/v0.0.3...1.1-rc.2 
- https://www.diffchecker.com/6YihSuMP
=> Add graviAura 1.1 upgrade script

data/badger/timelock/upgrade_graviAURA_strategy_V1_1/0x70861df8a1696e50a767424027c44a2ed937c52eae8cb7a4d396d3251786daa6.json
Relates to issue #577 
Tx: https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/0xd639632bc83411092b7c1d90a75bfc00a992faeaaa0ef682545efbd21400fbe4
=> feat: vestedaura upgrade data

helpers/addresses.py
=> feat: added new techops signer

great_ape_safe/ape_api/balancer.py
Tackles comments over [here](https://github.com/Badger-Finance/badger-multisig/pull/596#discussion_r908675287)
=> update: tigher assert on unstakes

helpers/addresses.py, scripts/issue/209/vote_to_drain_agent.py
see #209 for details
deadline to exec this is in roughly ~71 hours
=> script: vote to drain the aragon agent wallet of crvrenbtc

scripts/badger/claim_tree_rewards.py
=> fix: include graviaura in claim tree snapshot

helpers/addresses.py, scripts/issue/651/rate_emissions_b80BADGER-20WBTC.py
This PR tackles #651 and relates to https://github.com/Badger-Finance/badger-rewards/issues/909
Run with:
```
brownie run scripts/issue/651/rate_emissions_b80BADGER-20WBTC.py
```
=> feat: rate emissions 80badger20wbtc

great_ape_safe/ape_api/balancer.py, scripts/issue/642/adjust_bpt_bootstraps.py
issue #642 
edit: withdraws all from the aura and aurabal bpt straight to the vault msig
=> script: unwind aura and aurabal bpt to vault

helpers/addresses.py, scripts/issue/655/digg_tcl_migration.py
Tackles #655 
To run in this order: 
```
brownie run issue/655/digg_tcl_migration graviaura_transfer
brownie run issue/655/digg_tcl_migration migrate
```
Pushing it to have ready for the treasury decision output if ✅ as discussed during call, nice if post as soon as it is possible
=> Scripts for digg tcl migration to balancer/aura eco

scripts/issue/617/withdraw_all_rari.py
handles #617, tx is built manually because of same issue mentioned [here](https://github.com/Badger-Finance/badger-multisig/issues/500#issuecomment-1138845414) when withdrawing previously
=> withdraw all from rari script

great_ape_safe/ape_api/aave.py, great_ape_safe/ape_api/uni_v3.py
handles #658
levering:
```py
SAFE.aave.deposit(WBTC, 5e8)
SAFE.aave.lever_up(WBTC, USDC, .5)
```
sushiswap:
```
balance_before         balance_after         balance_delta
symbol                                                                  
aWBTC   0.000000000000000000  7.502991230000000000  7.502991230000000000
```
uni v3:
```
balance_before         balance_after         balance_delta
symbol                                                                  
aWBTC   0.000000000000000000  7.521543920000000000  7.521543920000000000 
```
=> use uni v3 for aave lever/delever

scripts/issue/662/voter_delegate_itself.py
Tackles #662 
```
brownie run issue/662/voter_delegate_itself
```
=> Delegate aura lock in voter to itself

scripts/issue/623/add_executor_to_acl.py
Tackles #623
Run with:
```
brownie run scripts/issue/623/add_executor_to_acl.py
```
Simulation:
```
brownie run scripts/issue/623/add_executor_to_acl.py main true
```
=> feat: script to add executor to keeper ACL

helpers/addresses.py, interfaces/badger/IBadgerRegistryV2.sol, scripts/issue/679/setup_registry_acl.py
Tackles issue #679 
Run with:
```
brownie run scripts/issue/679/setup_registry_acl.py
```
Simulate with:
```
brownie run scripts/issue/679/setup_registry_acl.py main true
```
=> feat: registry_acl setup script

scripts/issue/663/set_aura_bribes_processor.py
=> fix: code for processor setting works

scripts/issue/689/settle_voter_positions.py
handles #689
```
brownie run issue/689/settle_voter_positions mint_aurabal_and_lock_aura
```
```
brownie run issue/689/settle_voter_positions sell_bal_for_wbtc
```
=> script for staking/selling bal + locking aura

scripts/snapshot/AURA/vote_proposal.py
Had this locally since [this](https://discord.com/channels/785315893960900629/999748268420501686/999801064394084352) tx was posted, but never pushed. Leaving it here for the records, and probably will be updated after #686 gets merged
=> Fix the script for voting into the aura proposals

great_ape_safe/ape_api/snapshot.py, great_ape_safe/great_ape_safe.py
handles #677, still more to explore with api. drop suggestion/feature request here
idea is that vote can be posted as such through scripts:
```py
voter = GreatApeSafe(r.badger_wallets.treasury_voter_multisig)
safe.init_snapshot(proposal_id)
safe_tx = safe.snapshot.vote("yes") or safe.snapshot.vote({"80/20 BADGER/WBTC": 1})
voter.post_safe_tx(safe_tx=safe_tx)
```
so far only supports single and weighted voting, not sure if other types are needed. full list [here](https://docs.snapshot.org/proposals/voting-types)
=> snapshot class, vote method

great_ape_safe/ape_api/snapshot.py, scripts/snapshot/AURA/vote_proposal.py
=> refactor vote script

helpers/addresses.py, interfaces/hiddenhand/IAuraBribe.sol, scripts/badger/bribe_hh.py
handles #708
```
brownie run badger/bribe_hh <badger_bribe_in_aura> <badger_bribe_in_balancer>
```
=> bribe through hh script

helpers/addresses.py, interfaces/badger/IAuraBalStaker.sol, scripts/issue/720/migrate_baurabal_strategy.py
Tackles issue #720 
Run with: 
```
brownie run scripts/issue/720/migrate_baurabal_strategy.py
```
Simulation:
```
brownie run scripts/issue/720/migrate_baurabal_strategy.py main true
```
=> feat: baurabal strat migration script

scripts/issue/723/bbausd_fee_and_type_change.py
Tackles #723 
Script to change MetaData:
```
brownie run scripts/issue/723/bbausd_fee_and_type_change.py change_vault_type
```
Script to change WD fees:
```
brownie run scripts/issue/723/bbausd_fee_and_type_change.py change_vault_withdrawal_fee
```
=> feat: bbausd fee and type change script

great_ape_safe/ape_api/badger.py, great_ape_safe/great_ape_safe.py, scripts/badger/claim_hh.py
handles #709
```coffeescript
brownie run badger/claim_hh
```
=> claim bribes from voter script

great_ape_safe/ape_api/cow.py, helpers/addresses.py, scripts/badger/process_bribes_graviaura.py
=> Modify scripts to use updated aura bribes processor 

scripts/signers_framework/signers_analysis.py
Tackles #717. Uniquely the participation analysis, leaving the time reaction for later time.
```
brownie run signers_framework/signers_analysis
```
=> script to analsysis signers participation under specific time interval

great_ape_safe/ape_api/snapshot.py
handles #725
for testing new functionality:
```yml
brownie run snapshot/AURA/vote_proposal
```
=> improve voting verification

great_ape_safe/ape_api/snapshot.py
we found some tiny bugs when testing in prod, which of course for a hash always matter. dtype for the weighted choice has to be `dict` and for the single choice has to be `int`.
was successfully able to reproduce the sigs produced by posting the same vote through the ui:
```
>>> voter.init_snapshot('0x632726577e9c186a8827311b8702dcfd98f26376237b9715e64eafa61d6d7672')
>>> voter.snapshot.create_payload_hash(timestamp=1660916596, choice={'80/20 BADGER/WBTC': 1})
msg hash: 0x4f7a4ac87a416dfe0b64b26613bedbdda8bb408da76bc2da4274d1ef8a34e1e8
```
and
```
>>> voter.init_snapshot('0x89b36c1571aa9d55e2c692a3524ec80ce4ef9668b3cb796da42e13c5b3462235')
>>> voter.snapshot.create_payload_hash(timestamp=1660923084, choice='Yes')
msg hash: 0xf393f8ace6ff7dcaab84e11d1bb7a577d5f6e797bdc5f275e653a6eb4c5a55a7 …
```
=> fix: pass correct dtype for choice and drop metadata if empty

scripts/issue/759/upgrade_uni_lp_geyser.py
solution for #759 and part of #747
=> script: upgrade uni lp geyser in order to sweep

helpers/addresses.py, interfaces/badger/IVestedAura.sol, scripts/issue/773/upgrade_graviaura.py
Tackles issue #773 
Upgrade script for graviAURA + sets redirection path for BADGER atomically.
Queue:
```
brownie run scripts/issue/773/upgrade_graviaura.py main
```
Execute:
```
brownie run scripts/issue/773/upgrade_graviaura.py main false false
```
Simulate:
```
brownie run scripts/issue/773/upgrade_graviaura.py main false true
```
=> graviAURA v1.2 upgrade script

helpers/addresses.py
=> chore: add goerli testnet msig to addresses

great_ape_safe/ape_api/badger.py, scripts/issue/729/deprecate_polygon.py
- deprecates remaining 3 polygon vaults
- solve #729
=> chore: add script for polygon vault deprecation

great_ape_safe/ape_api/balancer.py, great_ape_safe/ape_api/convex.py, scripts/issue/807/withdraw_stables.py
=> withdraw treasury stables script

helpers/addresses.py
see #704 i guess.
addresses were never corrected on other chains.
=> chore: update executor4 address

great_ape_safe/ape_api/curve.py, helpers/addresses.py, scripts/issue/825/seed_fraxbp.py
=> seed badger/fraxbp pool

scripts/badger/process_bribes_graviaura.py
there was a bug (#834) for which this func was needed to solve
=> chore: add a way to sell a specific token present in the processor

helpers/addresses.py
deployed for q4. still need funding.
=> feat: add drippers for q4

scripts/issue/853/increase_pricer_slippage.py
=> script: increase slippage on both bvecvx and gravi pricers to max

scripts/issue/836/deposit_badger_fraxbp_lp.py
handles #836 
```
brownie run issue/836/deposit_badger_fraxbp_lp
```
=> deposit badger/fraxbp lp into convex

helpers/addresses.py, scripts/badger/bribe_ecosystems.py
tackles #873 & #847
still waiting on the following [question](https://discord.com/channels/866037423325446165/866039411258425385/1030126781585424424). somehow i believe that nobody bribe just yet cause there is a minor issue with that on the way is set, but i may be wrong. if you know the right approach, please lmk
=> Update bribing script to contain all ecosystems interested on and fix proposal index

scripts/issue/878/migrate_drippers_q3_q4.py
=> script: migrate keepers from q3 to q4 drippers

scripts/badger/voter_chores.py
Minor update in the script to keep it as the local copy i run today. it was missing the aura balance in the strategy at the moment of running the script
=> Add missing piece in `total_wd_aura` the naked aura idle in strategy

scripts/issue/888/rebalance_wbtc_weth.py
handles #888, now sells 40 wbtc ~submitting as draft - currently 38 naked wbtc that can be used for swap, but not sure if more wbtc should be siphoned from other sources in this pr for other TCL activities as mentioned in proposal~
=> sell wbtc for weth script

scripts/badger/aura_tcl_strategy.py
=> update aura tcl script

great_ape_safe/ape_api/cow.py
=> chore: update cow quote api endpoint

great_ape_safe/ape_api/balancer.py, scripts/balancer/gravi_stable_pool_creation.py
just some random hacking. didnt get it to work though. still `BAL#103`.
note the pool was already deployed by @hasherror here: https://etherscan.io/address/0x6A9603E481Fb8F2c09804ea9AdaB49A338855B90
=> fix: better integration into balancer class, random fixes

scripts/issue/908/trops_cleanup_q4.py
=> trops cleanup q4

helpers/addresses.py, scripts/issue/792/register_emission_control.py
closes #921 
closes #922 
solves #792
=> fix: pr #921 #922 but now with signed commits only

scripts/issue/791/deprecate_swapr.py
=> chore: add arbitrum swapr vault deprecation script

scripts/badger/process_bribes_graviaura.py
minor bug left from moving to new api endpoint (#388)
=> fix: reflect renaming on api endpoint

interfaces/defidollar/ICore.sol, scripts/issue/953/open_ibbtc.py
=> feat: open ibbtc for withdrawals script

great_ape_safe/ape_api/cow.py
see https://docs.cow.fi/front-end/creating-app-ids and https://explorer.cow.fi/appdata?tab=decode
=> feat: use proper `appData` hash hosted on ipfs

scripts/badger/aura_tcl_strategy.py
integrates #938 into #947 for this week and adjusts `coef` for bal swap in #923
=> add flag toclaim univ3 fees from aura tcl strat, change coef to 0.98

scripts/badger/aura_tcl_strategy.py, scripts/issue/967/deprecate_and_stop_emissions.py
Tackles #967 
Run with:
```
brownie run scripts/issue/967/deprecate_and_stop_emissions.py
```
Run upkeep withdraw with:
```
brownie run scripts/issue/967/deprecate_and_stop_emissions.py withdraw_link
```
=> feat: deprecate and stop emissions script

helpers/addresses.py, scripts/issue/931/voter_module_integration.py
Tackles #931 
```
brownie run issue/931/voter_module_integration enable_module
brownie run issue/931/voter_module_integration register_voter_module
```
=> Integrate voters module in msig

scripts/badger/process_bribes_bvecvx.py
Tackles #832 
Run simulation with:
```
brownie run scripts/badger/process_bribes_bvecvx.py step2 True
```
=> feat: cvx bribes processing dynamic split

great_ape_safe/ape_api/curve.py, scripts/warroom/emergency_swap.py
=> emergency stable swap script

scripts/issue/825/seed_fraxbp.py, scripts/issue/979/increase_badger_fraxbp.py
=> increase tcl in badger/fraxbp position script

scripts/badger/aura_tcl_strategy.py
=> sweep bvecvx in aura tcl strat

great_ape_safe/ape_api/convex.py, scripts/issue/979/increase_badger_fraxbp.py
handles https://github.com/Badger-Finance/badger-multisig/issues/979#issuecomment-1330945310
=> add lockAdditional to convex class and use in script

helpers/addresses.py, scripts/badger/convex_frax_tcl_strategy.py
tackles #995 
```
brownie run badger/convex_frax_tcl_strategy
```
=> Process convex-frax strategy rewards to dai

scripts/issue/634/set_governance_1_5_vaults.py
Tackles #634 
```
brownie run issue/634/set_governance_1_5_vaults
```
=> feat: update gov in open 1.5 vaults to timelock

scripts/issue/1018/stake_bpts_on_balancer.py
=> feat: stake all bpts in vault on balancer gauges

helpers/addresses.py, scripts/chainlink/bvecvx_module_integration.py
From techops:
```
brownie run chainlink/bvecvx_module_integration register_bvecvx_module
```
From voter:
```
brownie run chainlink/bvecvx_module_integration enable_module
```
=> Add integration script of bvecvx module in voter msig

scripts/issue/1014/conclude_team_vesting.py
=> conclude team vesting script

scripts/issue/1021/stake_work.py
=> stake WORK on techops

great_ape_safe/ape_api/balancer.py, great_ape_safe/ape_api/helpers/balancer/queries.py
=> Get latest functional gauge addr from subgraph

scripts/badger/process_bribes_bvecvx.py
following changes in #988 , should have been included there
=> fix: hotfixes for new structure of `ACTIVE_TOKENS`

helpers/addresses.py, scripts/issue/1031/wbtc_dao_migration.py
handles #1031 
```
brownie run issue/1031/wbtc_dao_migration
```
=> wbtc dao migration script

great_ape_safe/ape_api/badger.py, scripts/badger/whitelist.py
func only looked at governance and not strategist, while both are considered by the contract when approving contract access:
=> feat: also consider strategist when whitelisting

scripts/issue/1053/temp_increase_bvecvx_balance.py
=> feat: temp increase bvecvx balance on voter msig

helpers/addresses.py, scripts/issue/1063/restake_tcl_aura.py
solution to #1063
includes a call to script which solves #1048
=> feat: restake tcl positions to aura

scripts/issue/1061/withdraw_ribbon.py
=> feat: initiate withdraw from ribbon

great_ape_safe/ape_api/aura.py, great_ape_safe/ape_api/cow.py, scripts/badger/aura_tcl_strategy.py, scripts/badger/process_bribes_graviaura.py, scripts/treasury/cvx_divest_ladder_order.py
minor random fixes for edge cases i had to make locally
=> fix: minor edits needed for successful cowswap interaction

scripts/issue/1061/withdraw_ribbon.py
note: round 5 did not close yet, will need to wait for that in order to successfully execute.
#1061
=> feat: call to finalise withdrawal process

scripts/chainlink/increase_upkeep_gas.py
Tackles #1074 
```
brownie run chainlink/increase_upkeep_gas <upkeep_id> <gas_limit>
```
=> feat: allow increasing the gas limit for specific cl upkeep id

great_ape_safe/ape_api/chainlink.py, helpers/addresses.py
needed for cancelling jobs that are still registered on the old registry (ie for #926)
=> chore: maintain old registry in codebase

helpers/addresses.py, scripts/issue/1083/budgets_2023_q1.py
=> feat: distribute budgets for 2023 (q1)

scripts/gnosis/sunset_safe.py
script to handle #993, #1096, #1097 from cli
```sh
brownie run gnosis/sunset_safe main <safe address>
```
=> sunset safe script

scripts/badger/aura_tcl_strategy.py, scripts/issue/1117/sell_tcl_rewards.py
=> sell tcl strat rewards, adjust slippage/deadline

helpers/addresses.py, scripts/issue/1125/revoke_approvals.py
handles #1125 
```boo
brownie run issue/1125/revoke_approvals.py main techops.badgerdao.eth
```
```boo
brownie run issue/1125/revoke_approvals.py main dev.badgerdao.eth
```
=> revoke approvals script

great_ape_safe/ape_api/uni_v3.py, helpers/addresses.py, scripts/issue/1122/create_gtc_position.py
handles #1122, includes a `get_amount_out` method in the uni-v3 class to help dynamically set ranges
=> create uni-v3 gtc position

scripts/badger/aura_tcl_strategy.py
=> chore: not lock any aura

great_ape_safe/ape_api/cow.py
handles #1130
current flow:
check if involved assets exist on cg:
**yes** -> get cg rates and compare to cow, if diff is > than `pct_diff_threshold`, then confirm cow rate with user else continue as normal
**no** -> confirm cow rate with user
=> cowswap rate screening

great_ape_safe/great_ape_safe.py, helpers/addresses.py
prep for #1133 (updates gas watchlist) and #1144 (make sure acl actors have gas)
=> chore: add exec to addr book for gas station

scripts/upkeep_manager/set_config.py
Tackles #1152 
```
brownie run upkeep_manager/set_config  cancel_member
brownie run upkeep_manager/set_config  set_min_rounds_topup 5
brownie run upkeep_manager/set_config  set_rounds_topup 10
brownie run upkeep_manager/set_config  pause
brownie run upkeep_manager/set_config  unpause
=> Include config script to tinker params in upkeep manager and cancel members

scripts/badger/aura_tcl_strategy.py
=> send unlocked aura to treasury

great_ape_safe/ape_api/cow.py
=> query cg price api by contract address in cow.py

helpers/addresses.py, scripts/issue/1154/univ3_harvester_integration.py
Tackles #1154 
```
brownie run issue/1154/univ3_harvester_integration enable_module
brownie run issue/1154/univ3_harvester_integration add_member
```
=> Integrate univ3 harvester module'

great_ape_safe/ape_api/uni_v3.py, scripts/issue/1166/deposit_remaining_gtc.py
=> deposit remaining gtc in uni v3 position

scripts/badger/aura_tcl_strategy.py
check for badger to sweep from voter in weekly aura tcl strat script
=> sweep badger from voter to treasury

scripts/issue/1010/claim_and_sell_influence.py
adjusts `claim_and_sell_influence.py` for #1180
=> q1 claim and sell influence

.env.example, great_ape_safe/ape_api/cow.py, great_ape_safe/ape_api/curve.py, great_ape_safe/ape_api/helpers/coingecko.py, scripts/warroom/treasury_divest/aura.py, scripts/warroom/treasury_divest/bunni.py, scripts/warroom/treasury_divest/convex.py, tests/curve/conftest.py, tests/curve/test_curve_withdraw.py
=> calc curve withdraw amounts, add unwrap option to emergency scripts

great_ape_safe/ape_api/__init__.py, great_ape_safe/great_ape_safe.py
also undos changes so that the `init_` methods are defined explicitly. rationale here: https://discord.com/channels/1011322803414388897/1011333454740340756/1088208597986578582
=> organize ape apis in separate class

great_ape_safe/ape_api/aura.py, great_ape_safe/ape_api/convex.py, helpers/addresses.py, scripts/badger/aura_tcl_strategy.py, scripts/issue/1063/restake_tcl_aura.py
closes #1205
edit: also closes #1206
=> speed up aura/convex claiming process

requirements.txt, scripts/badger/bribe_ecosystems.py
Tackles #1211 
Since the TCD allows for $1-$5k/week, updating the script in this way will facilitate the runs imo
=> feat: allow passing arg as dollar denominated for bunni incentives

.gitignore, .gitmodules, README.md
this is the proper way to have a github repo in a repo. submodules can be updated through
```
git submodule update --init --recursive
```
=> feat: add votium repo as a proper submodule

interfaces/gnosis/IMultisigWalletWithDailyLimit.sol, scripts/issue/1234/sign_wbtc_sweep.py
=> feat: sign txs on wbtc dao msig

scripts/issue/1250/plug_voter_module.py
Tackles #1250
```
brownie run scripts/issue/1250/plug_voter_module
```
=> feat: include voter module in upkeep mngr.

scripts/issue/1105/sunset_arb1_dev_deprecated.py
@petrovska-petro this needs to be posted in a different way then usual.
the script currently assumes one of the owners can be loaded into brownie and post all txs that way. maybe not the safest way. another option would be to add frame support.
how did we do this in the past?
solution to #1105
=> feat: sunset deprecated dev msig on arb1

great_ape_safe/ape_api/badger.py
=> chore: remove min balance exception for `ops_deployer`

brownie-config.yaml, contracts/StakingRewardsSignalOnly.sol, helpers/addresses.py, interfaces/oz/IAdminUpgradeabilityProxy.sol, scripts/issue/1005/sweep_slp_geyser.py
solves #1005 
@sajanrajdev and or @petrovska-petro could you have a look before i go ahead and deploy the new logic?
=> feat: upgrade slp geyser and recover badger from it

data/badger/timelock/upgrade_slp_geyser/0x480d604d8222829deedf468332f123e3622b1bdebf4983420734b55176d1a198.json, data/badger/timelock/upgrade_slp_geyser/0x531b9378058d802f2b7168672c71c53d33bc7faff3434a33f1bb29e1edd31977.json, scripts/issue/1005/sweep_slp_geyser.py
=> chore: upload timelock queue data

scripts/badger/claim_voter_hh.py
tackles #1284
```
brownie run scripts/badger/claim_voter_hh
```
=> feat: claim from hh rewards and send to trops

scripts/issue/1321/remove_graviAURA_keeper.py
=> feat: remove graviAura's keeper

scripts/issue/1331/sign_wbtc_tx.py
=> feat: confirm txid 3 on wbtcdao msig

great_ape_safe/ape_api/bunni.py, helpers/addresses.py, scripts/issue/1343/bunni_migration.py
Tackles #1343 
```
brownie run scripts/issue/1343/bunni_migration
```
=> feat: bunni migration - treasury decision

scripts/issue/1338/deprecate_avatars.py
Tackles #1338 
```
brownie run scripts/issue/1338/deprecate_avatars
brownie run scripts/issue/1338/deprecate_avatars stop_automation
```
=> feat: migrate avatar liq to vaultmsig and stop upkeeps in mngr

scripts/issue/1325/sell_stables_q4_budget.py
tackles #1325 
```
brownie run scripts/issue/1325/sell_stables_q4_budget
```
=> feat: dai -> usdc order to reach budget req

helpers/addresses.py, scripts/badger/liquis_tcl_strategy.py
tackles #1405
```
brownie run scripts/badger/liquis_tcl_strategy
```
=> feat: enable liquis initial tcl logic

scripts/issue/1424/change_ibbtc_signers.py
=> feat: swap ibbtc signers for Trops'

scripts/issue/1461/rembadger_management.py
=> feat: rembadger management

helpers/addresses.py
=> feat: added new payments multisig

data/badger/timelock/upgrade_slp_geyser/0xaefafc885744e7c56e22b594e7cdd5ac6472ba2c375f89d0f4ef259f4e4c77ce.json, data/badger/timelock/upgrade_slp_geyser/0xbfe30d239cafd07f1f3e62ed4e8f72edfedc8ffbb0c4f436ce4f651a211c75ba.json, data/badger/timelock/upgrade_slp_geyser/0xf454b858d110f2561a16783d86c7cd192a2f1337d334be3c41284941fe4bd192.json, scripts/badger/process_bribes_bvecvx.py, scripts/issue/1005/sweep_slp_geyser.py, scripts/issue/1380/aura_divest.py
Relates to #1005 
Few misc fixes pushed:
- Adapted the asset sweep list for the geyeser upgrade script (more assets have been transfered to Dev)
- Pushed the latest Votium data
- Extended the orders deadline for the AURA divestment
- Updated the geyser upgrade timelock data to the latest (may change again as it wasn't signed in time)
- Added GRAI to the assets to ignore from the bveCVX processing script (it breaks the flow as it doesn't adhere to ERC20)
=> Misc changes

scripts/badger/liquis_tcl_strategy.py
=> feat: transfer $liq to trops for incentives ops

README.md
=> docs: update signers list

great_ape_safe/ape_api/badger.py, helpers/addresses.py
=> feat: add mev bot to gas station watchlist

helpers/addresses.py
Tackles: https://github.com/Badger-Finance/badger-multisig/issues/1524
=> feat: add ebtc techops signers to watchlist

README.md
Relates to #1534 
Adds juanbug to Readme
=> feat: add signer to readme

README.md
=> docs: adapt readme
