great_ape_safe/great_ape_safe.py
helpers/addresses.py
interfaces/badger/IStrategy.sol
interfaces/pancake/IPancakeRouter01.sol
interfaces/pancake/IPancakeRouter02.sol
scripts/issue/58/disable_wd_fees_bsc.py

set wd fee to 0 on all bsc strats

---

interfaces/badger/IController.sol
interfaces/badger/IStrategy.sol
scripts/issue/57/set_rewards_to_treasury_ops.py

This PR closes issue #57 
As long as the strategist performance fee is set to 0, all performance fees go to the controller.rewards() for each strategy's controller. Withdrawal fees always go to this address.
Script that loops through all controllers and calls setRewards(treasury_ops_multisig) on them. Some controllers are governed by the Timelock so this call must be queued. Additionally, loops through all strategies and reports if any doesn't have its performanceFeeStrategist set to 0.
Note: The restitution controller and mStable controller were left out on purpose. Both of these have different fee processing structure.
Run the following to queue:
```
brownie run scripts/issue/57/set_rewards_to_treasury_ops.py
```
And to execute:
```
brownie run …
```

feat: change rewards to treasury ops

---

helpers/addresses.py
interfaces/defidollar/ICore.sol
interfaces/defidollar/IPeak.sol
interfaces/defidollar/IZap.sol
scripts/issue/78/grant_access_ibbtc_peak.py

This PR closes issue #78 
Grants contract access to the treasury_ops multi on both ibBTC peaks. The peaks are owned by the DefiDollar-Badger dual multi, so the txs are to be loaded there.
**NOTE:**The atomic tx had to be split as there was an `ExecutionFailure` when running the two together - couldn't figure out the reason. Txs go through when loaded independently. 
Run the following to approve on the Badger peak;
```
brownie run scripts/issue/78/grant_access_ibbtc_peak.py
```
And with the following to approve on the byvWBTC peak;
```
brownie run scripts/issue/78/grant_access_ibbtc_peak.py main byvwbtc
```

feat: approve contract access on ibbtc peaks

---

helpers/addresses.py
interfaces/aragon/IAgent.sol
interfaces/aragon/IVoting.sol
interfaces/badger/IBalanceChecker.sol
interfaces/badger/IProxyAdmin.sol
interfaces/badger/ISimpleTimelockWithVoting.sol
scripts/issue/71/consolidate_badger.py

This PR tackles issue #71 
The script is split into two parts:
- Upgrades the logic of the DAO_treasury contract to the newly deployed logic which changes the beneficiary of the release() function.
- Upgrade performed on the old_proxyAdmin directly from the the [Ops_Multisig_old](https://gnosis-safe.io/app/eth:0x576cD258835C529B54722F84Bb7d4170aA932C64/transactions/queue).
Run Part 1 with:
```
brownie run scripts/issue/71/consolidate_badger.py main false true
```
- Releases all the BADGER from the DAO_treasury into the devMulti
- Checks for the deficit between the bBADGER strat staked balance and the Geyser balance and fills out the Geyser to this amount
- Calls `controller.withdrawAll(BADGER)` to move all BADGER from the strat to the vault (Reverts unless there is enough balance on the …

feat: script to consolidate badger

---

data/badger/timelock/set_rewards_to_treasury_ops/0x33dac5d2618088df29e2de3eee3e809441ecab7705feb2ccad263fdbabab100a.json
data/badger/timelock/set_rewards_to_treasury_ops/0xca0d48afce71bfaa44ff1a46910a24ced38e729da0a905eb0d9136722f6c34ef.json
data/badger/timelock/set_rewards_to_treasury_ops/0xdac70473101f62ff5de46a0678120ce9065d65d483b126e04db4cdd9e4411b7b.json
scripts/issue/57/set_rewards_to_treasury_ops.py

This PR relates to issue #57 
Adds the payload data from the rewards address change on the controllers governed by the Timelock.

feat: set rewards payload data

---

great_ape_safe/ape_api/badger.py
great_ape_safe/ape_api/cow.py
scripts/badger/claim_bribes.py
scripts/badger/swap_bribes_for_bvecvx.py

- added more `try/except`s to make things easier
- cowswap func now has feature to sell at x% of quoted market price
- script is now so generalised it can be run every round, as long as we keep `data/Votium/merkle/` updated through `git pull` and add new bribe tokens to `registry.eth.bribe_tokens_claimable`

some more automation in the bribe claiming process

---

scripts/badger/claim_eps.py

Tackles the claiming portion of #183
Command:
```
brownie run --network bsc-main-fork badger/claim_eps
```
Note:
Grab the latest data from convex repo
```
git clone https://github.com/convex-eth/platform.git data/Convex_EPS
```

Port EPS claim script - using github data

---

scripts/issue/32/mint_lowest_range_uni_v3.py

ref: https://github.com/Badger-Finance/badger-multisig/issues/32#issuecomment-1054628718
Fix the range, wbtc amount deposited and wd all from ibbtc sett

Chore: Updating script as was run yesterday

---

scripts/issue/188/unstake_work.py

solves **#188**, testing that we can unstake WORK. claiming process on hold. runs on `polygon`:
`brownie run issue/188/unstake_work.py --network polygon-main-fork`

unstake WORK from opolis

---

scripts/issue/217/claim_dropt.py
scripts/issue/217/issue217.py

**solves #217**:  add script to claim tree reward from trops and redeem for bdigg and withdraw to digg(?)
run:
`brownie run issue/217/claim_dropt.py`

redirect and redeem outstanding dropt3 rewards to treasury ops

---

scripts/badger/claim_eps.py

Tackles 1st point of #277 
Grab latest files from [repo](https://github.com/convex-eth/platform)
Command:
```
brownie run --network bsc-main-fork badger/claim_eps
```
Output: `TOTAL EPS CLAIMED 41,557.060288641325314529`

Update claim script with last round of EPS claims

---

scripts/gnosis/single_transfer.py

this was used to post #295:
`brownie run gnosis/single_transfer main 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e 0x3472A5A71965499acd81997a54BBA8D852C6E53d 0x042B32Ac6b453485e357938bdC38e0340d4b9276 200000e18`

initialise a single token transfer from cli

---

helpers/addresses.py
interfaces/defidollar/IPeak.sol
interfaces/defidollar/IUpgradableProxy.sol
scripts/issue/204/upgrade_peak_and_sweep.py

This PR closes issue #204 
Upgrades the logic of ibBTC's BadgerSettPeak to add a sweep function for unprotected tokens. Sweeps the stuck bveCVX into the Treasury Vault multi.
Use the following to run:
```
brownie run scripts/issue/204/upgrade_peak_and_sweep.py
```

Script to Upgrade BadgerSettPeak and Sweep bveCVX

---

great_ape_safe/ape_api/badger.py
interfaces/badger/IBadgerRegistry.sol
scripts/badger/registry.py

This PR sill be used totackle issue #229 
Adds a function to the Badger API to set keys on the registry as well as a general script to interact with this function directly from the console. Use the following to run:
```
brownie run scripts/badger/registry.py set_key KEY Target_Address
```
For example:
```
brownie run scripts/badger/registry.py set_key GAC 0x9c58B0D88578cd75154Bdb7C8B013f7157bae35a
```

Script to add keys to registry from console

---

great_ape_safe/ape_api/pancakeswap_v2.py
great_ape_safe/ape_api/solidly.py
great_ape_safe/ape_api/spookyswap.py
great_ape_safe/ape_api/sushi.py
great_ape_safe/ape_api/uni_v2.py
great_ape_safe/great_ape_safe.py
helpers/addresses.py
scripts/issue/333/swap_dfd_comp_for_oxd.py

- adds `SpookySwap` class to api.
- `swap_usdc_for_oxd` in #346 now first swaps usdc -> wftm through spooky then swaps wtfm -> oxd through solidly. results in **~22% more oxd**
- revised the ever expanding `GreatApeSafe.init_all`

spookyswap class, better routing for swapping to oxd

---

scripts/issue/366/fix_bveoxd_addresses.py

Addresses #366
I'll transfer the fees earned after this is exec'd. Will post the txs in this thread
```
Events In This Transaction
--------------------------
├── Badger Vested Escrow OXD (0x96d4dBdc91Bef716eb407e415c9987a9fAfb8906)
│   └── SetTreasury
│       └── newTreasury: 0xf109c50684EFa12d4dfBF501eD4858F25A4300B3
│
└── Gnosis Safe (0x4c56ee3295042f8A5dfC83e770a21c707CB46f5b)
└── ExecutionSuccess
├── txHash: 0xa4bf3b62f80a89a629576aa6ec81212736b38d64fb9987e8847a43e202523b7d
└── payment: 0
```
```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x160402e20>,
│   'safe_address': '0x4c56ee3295042f8A5dfC83e770a21c707CB46f5b',
│   'to': '0x10B62CC1E8D9a9f1Ad05BCC491A7984697c19f7E',
│   'value': 0,
│   'data': …
```

Fix bveOxd address parameters

---

scripts/issue/435/badgerwbtc_withdraw.py

test withdrawal script from our badger/wbtc pool
`brownie run issue/435/badgerwbtc_withdraw.py `

balancer badger/wbtc withdraw script

---

great_ape_safe/ape_api/uni_v3.py

Tackles #446
Since we [claimed](https://etherscan.io/tx/0x780b8ec118eb57bdef2cfa446f65e08bc83807f7b44d1d4544a90d71a4a2ac92) recently the fees now there may not be any claims available to test it properly. For testing, please leverage the forking at specific block height or locally to explore the values returned in the `.call(params, block_identifier)`. Use block below **14856066**

update: only exec fee collection if there is any fee to be collected

---

great_ape_safe/ape_api/badger.py
great_ape_safe/great_ape_safe.py
helpers/addresses.py

- new contract method can build `Contract` object from an interface, from explorer or from existing `Contract`.
- in case `address` cannot be resolved to an actual address, the method will just return `None`
if on a chain for which no entry exists in the address book, `r` will just return an empty `DotMap()`. this can then safely be passed to `GreatApeSafe.contract`; it will just return `None`.

feat: add improved `contract` method

---

helpers/addresses.py
scripts/badger/registry.py

Migrate registry to registry v2 on Arbitrum.
```
brownie run scripts/badger/registry.py migrate_registry_keys --network abitrum-main-fork
```
Satisfies a partial of #365

chore: add minor patch migration + migrate arbitrum registry

---

interfaces/badger/ISettV4h.sol
scripts/issue/318/recover_user_assets.py

Tackles #318 
Sweeps stuck bSLP tokens stuck on itself, charges a 20% service fee, and transfers reminder to affected user.

feat: recover user stuck assets

---

helpers/addresses.py
scripts/issue/582/register_subdomains.py

Tackles #582 
```
brownie run issue/582/register_subdomains
```
**Note:** change name from bvecvx_voting_multisig -> treasury_voter_multisig already in the book. it may break some other scripts by the renaming ref to tackle #585

Register msigs in badgerdao.eth domain

---

scripts/issue/608/unstake_aurabal_and_rewards.py

Tackles #608 
```
brownie run issue/608/unstake_aurabal_and_rewards
```
**Note:** for the time being on gauge uncertainty, we leave naked the aurabal position in the msig

Unstake aurabal and lock aura rewards

---

scripts/issue/502/top_ups_for_q3.py

tiny adjustment made in the top up script to prevent staking in balancer and use the aura gauge instead.

fix: stake bpt in aura instead of balancer

---

great_ape_safe/ape_api/badger.py
great_ape_safe/ape_api/chainlink.py
scripts/issue/569/transition_dripper_upkeeps.py

solves issue #569 
canceling an upkeep and retrieving its $link needs to be apart at least 50 blocks:
```
brownie run issue/569/transition_dripper_upkeeps cancel_q2
```
```
brownie run issue/569/transition_dripper_upkeeps register_q3
```
to simulate the whole process:
```
brownie run issue/569/transition_dripper_upkeeps sim
```

script: cancel q2 upkeep and register new ones for q3

---

great_ape_safe/ape_api/badger.py
interfaces/badger/IGovernanceTimelock.sol

Locks interface to use when instantiating timelock to avoid brownie caching wrong interface issues

chore: lock timelock interface

---

helpers/addresses.py
interfaces/badger/IAuraBalStaker.sol
scripts/issue/633/migrate_baurabal_strategy.py

This PR tackles issue #633 
To post:
```
brownie run scripts/issue/633/migrate_baurabal_strategy.py
```
To run simulation:
```
brownie run scripts/issue/633/migrate_baurabal_strategy.py main true
```
NOTE: As part of the migration process, the naked bb-a-usd accumulated for the current strat will also be emitted.

BauraBAL strategy migration script

---

scripts/issue/690/claim_and_deposit_tcl.py

Tackles #690 
```
brownie run issue/690/claim_and_deposit_tcl
```
**Note:** added the tcl action into this pr, since it fits post-aura rewards claim. Bare in mind two of the limitations while reviewing:
1. max graviaura for depositing is 25k
2. max wbtc to deposit is 6.5 wbtc into the tcl
Everything will depend on the spot prices at time of posting.

Claim rewards and deposit into bpt/aura tcl

---

scripts/badger/post_thresher_transfers.py
scripts/badger/thresher.py

These changes were used to be able to run the thresher in #511 due to block lock in `bvecvx` 
Added also the script which needs to be run post-thresher and remove the *BAL* claim, since it is likely the last one to come from trops.

Update threser around block lock and add post trasnfers script

---

great_ape_safe/great_ape_safe.py

`print_snapshot` functionality is blocked from [changes here](https://github.com/Badger-Finance/badger-multisig/pull/686/commits/119dfc62c506ec4d35b987760e33a1ba52496b44) ([rationale here](https://github.com/Badger-Finance/badger-multisig/pull/686#discussion_r935786358)). fixed by using `isinstance` instead for snapshot check

`print_snapshot` hotfix

---

scripts/issue/732/promote_aura_vaults.py

Tackles #732 
Promotes the following vaults to guarded state:
```
"bauraBal",
"b80BADGER_20WBTC",
"b40WBTC_40DIGG_20graviAURA",
"bBB_a_USD",
"b33auraBAL_33graviAURA_33WETH"
```
Run with:
```
brownie run scripts/issue/732/promote_aura_vaults.py
```

feat: aura vaults promotion script

---

great_ape_safe/ape_api/badger.py

fix: actual amount of tokens claimed is stored in `claimable` not in `claimMetadata.amount`

---

helpers/addresses.py
scripts/badger/refill_gas_arbi.py

Tackles issue #752 
To add Otpimism network and fork use: 
```
brownie networks add Optimism optimism-main host=RPC_URL chainid=10 explorer=https://optimistic.etherscan.io/
brownie networks add Development optimism-main-fork fork=opt-main cmd=ganache-cli host=RPC_URL chain_id=10 port=8545
```
The same script used for #679 on Ethereum can be used for the other side chains. Use the following to run:
**ARBITRUM**
```
brownie run scripts/issue/679/setup_registry_acl.py --network arbitrum-main-fork
```
**FANTOM**
```
brownie run scripts/issue/679/setup_registry_acl.py --network ftm-main-fork
```
**POLYGON**
```
brownie run scripts/issue/679/setup_registry_acl.py --network polygon-main-fork
```
**OPTIMISM**
```
brownie run scripts/issue/679/setup_registry_acl.py --network optimism-main-fork
```

Added missing sidechain addresses for RegistryACL setup

---

helpers/addresses.py

Note: looks like ibbtc/weth is no longer receiving rewards, deprecate vault

chore: update august swapr gauges

---

scripts/badger/process_bribes_graviaura.py

Tackles issue #760 
With these changes, only the BADGER sent to the processor will be accounted towards HODLrs hunted bribes. For the time being, BADGER bribes will be redirected to Treasury so, unless someone manually sends BADGER to the processor, no BADGER will be transferred there from the strat. It is likely that the balance of BADGER on the processor will be 0 and 25% of the wETH will be sold for BADGER to compensate.

feat: adapted sell weth script to check badger

---

scripts/snapshot/AURA/vote_proposal.py

handles #787 `gauge` can now be passed into `vote_proposal.py` with the value corresponding to `Gauges` enum

allow votes in different gauges in vote_proposal script

---

great_ape_safe/ape_api/badger.py
interfaces/badger/IVipCappedGuestListBbtcUpgradeable.sol
scripts/badger/guestlist.py
scripts/badger/registry.py

Tackles issue #757 
Introduces the following scripts to perform the following on the RegistryV2 and Guestlist with agility:
- Batch promote vaults from a list
- Batch demote vaults from a list
- Change metadata (the vault's behaviors allowed are limited to a list included in this PR - behaviors outside of this list are currently not being picked up by the UI's SDK).
- Change the user cap of a given vault
- Change the total cap of a given vault
- Remove the caps for a given vault
- Remove the caps for a batch of vaults

RegistryV2 and Guestlist scripts library

---

helpers/addresses.py
scripts/issue/797/set_pricer_on_processor.py

Tackles issue #797 
Sets a new pricer on the AuraBribesProcessor from devMulti. 
NOTE: Didn't add as generic script in order to incorporate a simulation - this shouldn't be an action that we perform often.
Run with:
```
brownie run scripts/issue/797/set_pricer_on_processor.py
```
Simulate with: 
```
brownie run scripts/issue/797/set_pricer_on_processor.py main true
```

Set AuraBribesProcessor pricer V3

---

helpers/addresses.py
interfaces/badger/IStrategyAuraStaking.sol
scripts/issue/823/migrate_strategy_gauges.py

Tackles issue #823 
Script that migrates the underlying gauge of Aura strategies to a new one based on the Aura's PID for that gauge.
NOTE: The script will prevent the gauge migration if it finds the new base rewards pool to empty. As per @GalloDaSballo, "We need more than 1e18 ppfs to avoid a rebase of the ppfs over time".
Run with:
```
brownie run scripts/issue/823/migrate_strategy_gauges.py
```
Run simulation with:
```
brownie run scripts/issue/823/migrate_strategy_gauges.py main true
```

Aura gauges migration script

---

great_ape_safe/ape_api/balancer.py
scripts/issue/899/unwind_baurabal_into_weth.py

Tackles #899 
```
brownie run issue/899/unwind_baurabal_into_weth
```
```
snapshot result for 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e:
balance_before             balance_after               balance_delta
symbol                                                                                   
bauraBAL  32,224.401157316469331838      0.000000000000000000  -32,224.401157316469331838
WETH       1,251.085491959735165736  1,619.203334969477595277      368.117843009742429541 
```

Unwind baurabal into weth

---

helpers/addresses.py
scripts/issue/753/bveoxd_unlock_and_deprecate.py

Tackles #753 
Run unlocking with:
```
brownie run scripts/issue/753/bveoxd_unlock_and_deprecate.py --network ftm-main-fork process_final_locks
```
Run deprecation with:
```
brownie run scripts/issue/753/bveoxd_unlock_and_deprecate.py --network ftm-main-fork deprecate_fantom_vaults
```

feat: oxd unlock and fantom deprecation

---

great_ape_safe/ape_api/convex.py
helpers/addresses.py
scripts/issue/930/frax_stake_badgerfraxbp.py

Tackles #930 
Vault creation:
```
brownie run issue/930/frax_stake_badgerfraxbp create_vault
```
Deposit in private vault:
```
brownie run issue/930/frax_stake_badgerfraxbp stake_in_vault
```
~**Note:** Leave it for now in draft since the vault creation is reverting with the following~
Seems related with the pool being deactivated temp [tx](https://etherscan.io/tx/0x8409c611fcb02054a9bc30298b8885cd507909fefb0d8e68e84ec5a7e430d5eb#eventlog)
There appear to give another pid (*35*) for the same staking token, passed manually at the end, since there is duplicates with *33* as deactivated and hits first in the `get_pool_pid`
**Note:** for testing create a separate ganache instance and run in order: 1st `create_vault` then `stake_in_vault`

Stake curve badgerfraxbp in frax gauge via private vault

---

helpers/addresses.py

no longer being used for badger activities: https://etherscan.io/address/0xC6a902de22b10cb176460777ce6e7A12A6b6AE5a

chore: remove deployer5 from active ops_ addresses

---

scripts/issue/944/gov_cleanup.py

handles #944
set gov for deprecated v1 vaults to `governanceTimelock`
```
brownie run issue/944/gov_cleanup set_new_gov
```
update system contracts from old proxy admins to `devProxyAdmin`
```
brownie run issue/944/gov_cleanup change_new_proxy_admin(<proxy_owner>)
```

governance 2.0 stage 1 cleanup script 

---

data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x01b9a3a35cda58b5166b0ee3eabca6a499e7fec6bd3eba6e9fae2c2736c0822d.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x1dad77f1156ee39277baa2dc2e8251183099f59646357cc5d7641e454135d6cf.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x26c4bd7016b7d7ea4718c7e0ae17ade809780b1340fbdfb5bcfb8629e5feb7d5.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x28e7409cbce49338d7bbb4eadd9b565b1495675522a66fc673a69bf2e07768b4.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x30948efbbe42e3b5636d20ddfa03376ff91b9e3ff903af2d73bfd5cfdcea3dea.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x35ac96c50ec6cce42ca65b19686099cf411b96e0f9ebf759cb29d79a9a024cc2.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x39ae02a8dfd8de9829458118a8b2e8a94afebac6cd386b0e581e4e34766dadc7.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x43b6af05d1721393cf6e596b2425a2bbe744938d2fd26f9434b6f1822882f18a.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x655884dda0f3c60030c17cf8bf5a2540241a18c453f57e00facac638928e262c.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x72cb709d023aca0a20452da9017903451910cd1c470388c7efb2057220b3cdb6.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x8e4c9e213ebac5b0b00ba8033017bf225b15a8d8f21fc4d4d2abdfa634bb5756.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x98bcea4d78bdd51b168f5c022dda04908b6430d6138fcf8af8e7c99fe058230f.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x9a4bbd9bcfa7fa7d544ed45b655013ccf65b71f961ae98808e0051cc76250f0e.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0x9e00622033d5320af002654b244c9b8f6c2b0562d1bdc30d2c5c095b4c2cc6b0.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xaf9f8063e694122ca57449b3d9ea6248a7ef6e8cdaf8180322f1653027b5dbe3.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xb04ba763cd63d04440202f3512272f34ee4c2934e16f498f8539500e19771da7.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xb250c486238a067546dd5d8914f040d49e348c35aaf7794ce51a147c020619ea.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xb9d97986db8ca1839c1ca408e6b9dd55e7588b7b79560e7a508cab5672865120.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xcc77767e4dbe0410cdf30fd457cef7b22dd23d5ea767add44179d735f680c648.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xd7c17ea35b9a72803aa771f786c6ac9c0a8f9a4a7e8e1618a00007348c1df96f.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xe501fc29fff4f37419d6cfb32daa46912f940d003072bfadf80c4784185962cb.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xefcb974e16bd72eaaec60e1cddaf7e6aa5a17cabcadad5f08f8df1caaf663922.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xf94994e38c7a628f48d59e43a5facf92b57370890b50813f95d31b5334a90df5.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xf9dc1edd4026e807d6d6ca18940d88b774b6a265f36a4b7386940c83f52e3b05.json
data/badger/timelock/change_admin_brick_upgradability_deprecated_vaults/0xfc56d279a71f93d30f49cfe61f5aeedf5edf1b465e9258209cb980c31986d818.json
scripts/issue/940/brick_deprecated.py

related to #948 
files required to later run the execution of queued txs, also includes the delay change to 7 days as it was requested by @dapp-whisperer at posting time and naming changes in the folder created to signal better the purpose for the records

chore: upload json files of queue tx for bricking upgradability

---

great_ape_safe/ape_api/convex.py

Tackles #1023 
Since currently aura is undergoing the migration, whole system is under `shutdown` mode, likely all pid will show in that state. Advisable to verify the fix to fork other older block, e.g: [16150058](https://etherscan.io/block/16150058)

Verify if specific pid is indeed active/shutdown

---

scripts/badger/audit_owners.py

@sajanrajdev my suggestion would something like this; add a flag for a simplified audit run.
with `audit_owners_mapper.py`:
```
roles = {
"0x96AC69183216074dd8CFA7A380e873380445EaDc": "find_me",
}
```
`$  brownie run badger/audit_owners find_roles_only` yields:
```
address,chain,label,threshold,owners,owner_role
0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327,poly,techops_multisig,3,0x96AC69183216074dd8CFA7A380e873380445EaDc,find_me
0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C,arbitrum,techops_multisig,3,0x96AC69183216074dd8CFA7A380e873380445EaDc,find_me
0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F,arbitrum,dev_multisig,3,0x96AC69183216074dd8CFA7A380e873380445EaDc,find_me
0x781E82D5D49042baB750efac91858cB65C6b0582,ftm,techops_multisig,3,0x96AC69183216074dd8CFA7A380e873380445EaDc,find_me
```

feat: add flag for simplified audit of signer roles

---

great_ape_safe/ape_api/__init__.py
great_ape_safe/ape_api/spookyswap.py
great_ape_safe/great_ape_safe.py

have been wanting to do this for a long time, but wasn't able to materialize it until now
- dynamically create `GreatApeSafe.init_{api_name}` methods from an api dict (`{init name: Module}`)
- dynamically build api dict from modules in `great_ape_safe/ape_api/`
consequentially, adding an api to GreatApeSafe now just requires to add a module to `great_ape_safe/ape_api/`.
naming patterns are the same with the previous manual interface naming, thus being backwards compatible with all existing scripts.
for naming it is assumed you are following [pep-8](https://peps.python.org/pep-0008/#class-names) guidelines
`init name`: `init_{file name}`
`Module`: class name
e.g:
`great_ape_safe/ape_api/uni_v3.py `
```py
class UniV3:
```
can be accessed through:
```py
safe.init_uni_v3(); safe.uni_v3
```

refactor great ape safe inits

---

helpers/addresses.py

deprecates some deployers and executors in order to be able to update the gas station watchlist
partial solve for:
- #1055 
- #1068 
- #1070

chore: update addresses for gas station watchlist

---

scripts/chainlink/upkeep_topup.py

Tackles #1106 
```
brownie run chainlink/upkeep_topup main 42960818007215227498102337773007812241122867237937589685113781988946396009556 2 89 2
```

Generalise upkeep topup script for legancy and latest cl registries

---

great_ape_safe/ape_api/badger.py
helpers/addresses.py
scripts/issue/1133/upkeep_manager_integration.py

Tackles 2 points from #1133 
For simulating the whole stack of txs:
```
brownie run issue/1133/upkeep_manager_integration sim
```
Commands to init the manager and test a complete cycle of addition of a dummy dripper, cancellation and see keeper wd the funds once they are avail:
```
brownie run issue/1133/upkeep_manager_integration initial_setup_and_testing
brownie run issue/1133/upkeep_manager_integration cancel_dummy_member
```
Final flow for the config is cancelling existing upkeeps and register them in the upkeep manager by:
```
brownie run issue/1133/upkeep_manager_integration cancel_upkeeps
brownie run issue/1133/upkeep_manager_integration register_members_in_manager
```
~While doing the script I realised that the gas st is registed in the old cl registry, and the upkeep manager was …

Integrate upkeep manager in gas st and add existing upkeep ids members

---

interfaces/euler/IDebtToken.sol
scripts/warroom/treasury_divest/euler.py

Tackles #1189 
~The pr tries to tackle imo two different types of withdrawals that we can have, the softer considering ownership and utilisation ratios and the max-out approach, which solely cares about what is available in the market as idle capital and check the minimum between our total “ebalance” and the available amount.~
~Somehow, made me realised that even at the time of emerg, we kind of tackle the best outcome scenario for us, only it could get reverted if other depositors tried to wd at the same time interval between [t_tx_posting, t_tx_exec] and its more than the `EXEC_SLIPPAGE` reduction.~
Let me know if you think there is a neater approach or I am missing some caveat. read comments below
--------
Uses the approach of the min amount between the max avail amount in the market …

feat: add two approach for wd: softer and max-out

---

great_ape_safe/ape_api/badger.py
helpers/addresses.py
scripts/issue/1198/fee_module_integration.py

Tackles #1198 
```
brownie run scripts/issue/1198/fee_module_integration enable_module
brownie run scripts/issue/1198/fee_module_integration add_member
```
I think that given the 2m in gas limit for this upkeep id, it may revert when adding the member, since it will require more eth funds. since already at 1m it will require ~121 link

feat: integrate fee collector module

---

scripts/issue/1264/mint_bottom_range_uni_v3_badgerwbtc.py

solution for #1264 
there is one json missing in our data folder for position 255188 (https://opensea.io/assets/ethereum/0xc36442b4a4522e871399cd717abdd847ab11fe88/255188) ranging from 326940 to 333960
this script results minting a range of 333960 to 340920

feat: mint next bottom range uni v3 badgerwbtc

---

great_ape_safe/ape_api/cow.py
scripts/badger/process_bribes_graviaura.py

this week the weth to aura swap expired. using `buy_aura_or_badger` we can now fix such situations, by passing any erc20 address (weth in this case)
also made a slight change in `cow.py` so that we can actually read api's error response before raising (the requests' response content contains more info that the raise):
```
FEE AND QUOTE PAYLOAD:
{'buyToken': '0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF',
'from': '0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e',
'kind': 'sell',
'sellAmountBeforeFee': '3023728579871303680',
'sellToken': '0xba100000625a3754423978a60c9317c58a424e3D'}
FEE AND QUOTE RESPONSE:
{'errorType': 'SellAmountDoesNotCoverFee', 'description': 'The sell amount for the sell order is lower than the fee.', 'data': {'fee_amount': '0x4f0dbc3ae0b47c00'}}
```

feat: sell arbitrary token stuck in processor

---

scripts/avatars/migrate_pids.py
scripts/avatars/transfer_ownership.py

Tackles #1298 
Ownership transfer:
```
brownie run scripts/avatars/transfer_ownership 
```
Funds migrations to new pids:
```
brownie run scripts/avatars/migrate_pids
brownie run scripts/avatars/migrate_pids sim
```

feat: avatar ownership transfer, prep for aura pid migrations and remaining funds into avatars

---

data/badger/timelock/upgrade_slp_geyser/0xfb73cc5ade077cef35bee6c26c6427057d6f5b212a88d908f3f2d4b5b3ab66c2.json
great_ape_safe/ape_api/badger.py
scripts/warroom/pause_deposits.py

Simple script to pause deposits on a v1.5 vault from dev Multisig as needed.
Use as:
```
brownie run scripts/warroom/pause_deposits.py main vault_address
```

Vault v1.5 deposits pausing helper

---

scripts/badger/bribe_ecosystems.py

closes #1280
the factor was provided to us via tg:
for testing run against the last [prop](https://gaugevotes.aura.finance/#/proposal/0xef2fc2401e5d3c1dd71488109d21b0aed91b736d9880825d491cfa5fd9c69958) and dd [here](https://api.hiddenhand.finance/proposal/aura)

feat: include snap factor diff from the migration to `gauges.aurafinance.eth` space

---

helpers/addresses.py
interfaces/paladin/IQuestBoard.sol
scripts/badger/bribe_ecosystems.py

Tackles #1396 
```
brownie run scripts/badger/bribe_ecosystems
```
Use for testing following params:
```
....
badger_bribe_in_liquis=1000,  # NOTE: the incentive gets process via Paladin
duration_paladin_quest=1,  # Duration (in number of periods) of the Quest
reward_per_vote_liquis=0.006,
....
```

feat: include paladin support for bunni/liquis incentives

---

great_ape_safe/ape_api/balancer.py
scripts/issue/1443/digg_lp_divestment.py

Tackles #1443 and #1380 and TCD1 (withdraw BADGER/wBTC LP)
Atomically:
- Withdraws BADGER and DIGG LP from Aura -> Balancer and unrwaps them
- Doesn't claim rewards from gauges (to be claimed afterwards on TCL strats)
- Sells graviAURA from Digg BPT for wETH as per TCD 36
- Burns DIGG (can't transfer to AddressZero so transfering to address(dead)
Run with
```
brownie run scripts/issue/1443/digg_lp_divestment.py
```

feat: aura lps divestment

---

helpers/addresses.py
scripts/badger/bribe_ecosystems.py

tackles partially #1437 to enable hidden hands support for liquis incoming epoch
address [ref](https://docs.redacted.finance/resources/contract-addresses/hidden-hand-contracts)
NOTE: bare in mind that if the epoch is off, it may trigger a revert in the tx during your local test, to see whole successful flow either ping a block where epoch was running before timestamp expired or wait till new one is mined

feat: include hh liquis support

---

helpers/addresses.py
interfaces/paladin/IQuestBoard.sol
scripts/badger/bribe_ecosystems.py

closes #1468 
params for testing:
```
badger_bribe_in_aura=0,
badger_bribe_in_balancer=0,
badger_bribe_in_votium=0,
badger_bribe_in_frax=0,
badger_bribe_in_bunni=0,  # NOTE: dollar denominated. Badger calculation is done internaly
max_tokens_per_vote=0,  # Maximum amount of incentives to be used per round (Hidden Hands V2)
periods=1,  # Rounds to be covered by the incentives deposited (Hidden Hands V2)
badger_bribe_in_liquis=2000,  # NOTE: dollar denominated. Badger calculation is done internaly, the incentive gets process via Paladin
duration_paladin_quest=1,  # Duration (in number of periods) of the Quest
reward_per_vote_liquis=0.001,  # Amount of reward per vlLIQ
liquis_incentive_in_paladin=True,  # Indicates if the incentive is going to be post in paladin or HH …
```

feat: allow possibility of using #liq as incentive in liquis marketplace paladin

---

scripts/issue/1277/mint_controller_admin_update.py

Tackles latest reccoms in #1277

feat: add tests after ownership is transfer to assert behaviours

---

helpers/addresses.py
scripts/issue/1489/assoc_and_treasury_council_funding.py

tackles #1489 and #1491
run:
1st step
```
brownie run scripts/issue/1489/assoc_and_treasury_council_funding sell_stable_for_usdc
```
2nd step once cow swaps are settled
```
brownie run scripts/issue/1489/assoc_and_treasury_council_funding assoc_and_council_funding
```

feat: scripts for assoc and treasury council funding

---

scripts/issue/1513/claim_vested_liq.py

closes #1513
```
brownie run scripts/issue/1513/claim_vested_liq 
```

feat: claim $liq from escrow

---

helpers/addresses.py
interfaces/badger/IRemBadger.sol
scripts/issue/1518/upgrade_rembadger.py

Performs upgrade of remBADGER through the timelock. In addition, it atomically deposits on behalf of whitelisted user when executing upgrade given that user has transferred BADGER to governance multisig.
- New logic: https://etherscan.io/address/0xeeff9a69febaeae39883dbea1eb12db367b97120#code
- Old logic: https://etherscan.io/address/0x37336199b3e7c9b0fc61d4289e98ad494cc7d52c#code
- Diff: https://www.diffchecker.com/bkZ8CAaF/
- BIP 103 (Amendment 3) shows user and amount: https://forum.badger.finance/t/bip-103-restitution-amendments/6184
Queue:
```
brownie run scripts/issue/1518/upgrade_rembadger.py queue
```
Execute: 
```
brownie run scripts/issue/1518/upgrade_rembadger.py execute
```
Simulation
```
brownie run scripts/issue/1518/upgrade_rembadger.py simulation
```

feat: upgrade rembadger 2.0

---

scripts/issue/1536/divest_voter_cvx.py

Tackles https://github.com/Badger-Finance/badger-multisig/issues/1536
Run trops prereq:
```
brownie run scripts/issue/1536/divest_voter_cvx.py transfer_fees_to_voter
```
Run main script: 
```
brownie run scripts/issue/1536/divest_voter_cvx.py
```

feat: cvx and cvxcrv divest

---

great_ape_safe/ape_api/uni_v3.py
helpers/addresses.py
scripts/issue/1545/bip_105_execution.py

tackles #1545 
run:
```
brownie run scripts/issue/1545/bip_105_execution
```

feat: migrate univ3 badger/wbtc to badger/ebtc partially 50%
